import { useEffect, useMemo, useState, type ReactNode } from 'react';
import {
  Activity, AlertTriangle, ArrowRight, Ban, Bell, Check, ChevronDown, CircleSlash,
  Command, FileClock, FileText, Gavel, Hash, ListChecks, LoaderCircle, LogOut, Menu,
  MessageSquareWarning, Plus, Save, Search, Settings2, Shield, ShieldCheck, Siren,
  Trash2, UserRound, X,
} from 'lucide-react';
import {
  COMMAND_CATALOG, type Appeal, type AuditLog, type GuildConfig, type ModerationCase,
  type ProgressionLevel, type ProgressionPunishment, type PunishmentType, type Strictness,
} from '@apexbot/shared';
import { api, type Guild } from './api';

type View = 'automod' | 'progression' | 'cases' | 'logging' | 'bot' | 'commands';
type Resources = { channels: Array<{ id: string; name: string }>; roles: Array<{ id: string; name: string; color: string }> };
type Option = { value: string; label: string };

const nav: Array<{ label: string; items: Array<{ id: View; label: string; icon: typeof Shield }> }> = [
  { label: 'Moderation', items: [{ id: 'automod', label: 'Auto moderation', icon: ShieldCheck }, { id: 'progression', label: 'Progression ladder', icon: ListChecks }, { id: 'cases', label: 'Cases & appeals', icon: Gavel }, { id: 'logging', label: 'Logging', icon: FileText }] },
  { label: 'System', items: [{ id: 'bot', label: 'Bot settings', icon: Settings2 }, { id: 'commands', label: 'Commands', icon: Command }] },
];

export default function App() {
  const [auth, setAuth] = useState<'loading' | 'out' | 'in'>('loading');
  const [user, setUser] = useState(''); const [guilds, setGuilds] = useState<Guild[]>([]); const [guild, setGuild] = useState<Guild | null>(null);
  const [config, setConfig] = useState<GuildConfig | null>(null); const [cases, setCases] = useState<ModerationCase[]>([]); const [appeals, setAppeals] = useState<Appeal[]>([]); const [logs, setLogs] = useState<AuditLog[]>([]);
  const [resources, setResources] = useState<Resources>({ channels: [], roles: [] }); const [view, setView] = useState<View>('automod'); const [menu, setMenu] = useState(false); const [error, setError] = useState('');

  useEffect(() => { void api.session().then(async (session) => { if (!session.authenticated || !session.user) return setAuth('out'); const list = await api.guilds(); setUser(session.user.username); setGuilds(list); if (list[0]) await loadGuild(list[0]); setAuth('in'); }).catch(() => setAuth('out')); }, []);
  async function loadGuild(next: Guild) { setGuild(next); setConfig(null); setError(''); const [c, cs, a, l, r] = await Promise.all([api.config(next.id), api.cases(next.id), api.appeals(next.id), api.logs(next.id), api.resources(next.id)]); setConfig(c); setCases(cs); setAppeals(a); setLogs(l); setResources(r); }
  async function save(patch: Partial<GuildConfig>) { if (!guild || !config) return; const old = config; setConfig({ ...config, ...patch }); setError(''); try { setConfig(await api.updateConfig(guild.id, patch)); } catch (cause) { setConfig(old); const text = cause instanceof Error ? cause.message : 'Save failed.'; setError(text); throw cause; } }

  if (auth === 'loading') return <Loading />; if (auth === 'out') return <SignIn />;
  return <div className="console-shell">
    <TopBar guild={guild} guilds={guilds} user={user} choose={(id) => { const next = guilds.find((item) => item.id === id); if (next) void loadGuild(next); }} menu={() => setMenu(true)} />
    <SideBar view={view} open={menu} pending={appeals.filter((item) => item.status === 'pending').length} select={(next) => { setView(next); setMenu(false); }} close={() => setMenu(false)} />
    {menu && <button className="scrim" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <main className="workspace">
      {error && <div className="error-bar"><AlertTriangle /><span>{error}</span><button onClick={() => setError('')}><X /></button></div>}
      {!guild ? <Empty icon={<Ban />} title="No available server" text="ApexBot must be installed and you need Manage Server permission." /> : !config ? <Loading compact /> : <Page view={view} config={config} cases={cases} appeals={appeals} logs={logs} resources={resources} save={save} />}
    </main>
  </div>;
}

function SignIn() { return <div className="signin">
  <header><Logo /><span>CONTROL SURFACE / 01</span></header>
  <main><section className="signin-copy"><p className="eyebrow">ApexBot server control</p><h1>KEEP<br />ORDER<span>.</span></h1><p>Set moderation rules, review cases, and control every action from one place.</p><a href="/api/auth/discord"><DiscordMark />Sign in with Discord<ArrowRight /></a><small>Manage Server permission required.</small></section><section className="signin-mark" aria-hidden="true"><div className="red-plane" /><div className="wire" /><b>A</b><span>APEX<br />MODERATION</span></section></main>
  <footer><span>APEXBOT</span><span>DISCORD / MODERATION / FTC</span></footer>
</div>; }

function TopBar({ guild, guilds, user, choose, menu }: { guild: Guild | null; guilds: Guild[]; user: string; choose: (id: string) => void; menu: () => void }) { return <header className="topbar"><button className="menu-button" onClick={menu}><Menu /></button><Logo /><div className="system-line"><i />SYSTEM ONLINE</div><div className="top-actions"><Dropdown compact value={guild?.id ?? ''} options={guilds.map((item) => ({ value: item.id, label: item.name }))} placeholder="Choose server" onChange={choose} /><span className="account"><UserRound />{user}</span><button className="icon-button" title="Sign out" onClick={() => void fetch('/api/auth/logout', { method: 'POST' }).then(() => location.reload())}><LogOut /></button></div></header>; }

function SideBar({ view, open, pending, select, close }: { view: View; open: boolean; pending: number; select: (view: View) => void; close: () => void }) { return <aside className={open ? 'sidebar open' : 'sidebar'}><button className="side-close" onClick={close}><X /></button><div className="rail-label">CONTROL</div>{nav.map((group) => <section key={group.label}><h2>{group.label}</h2>{group.items.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'active' : ''} onClick={() => select(id)}><Icon /><span>{label}</span>{id === 'cases' && pending > 0 && <b>{pending}</b>}</button>)}</section>)}<div className="side-foot"><Activity /><span>Gateway connected</span></div></aside>; }

function Page({ view, config, cases, appeals, logs, resources, save }: { view: View; config: GuildConfig; cases: ModerationCase[]; appeals: Appeal[]; logs: AuditLog[]; resources: Resources; save: (patch: Partial<GuildConfig>) => Promise<void> }) {
  const pages = { automod: <Automod config={config} resources={resources} save={save} />, progression: <Progression config={config} save={save} />, cases: <Cases cases={cases} appeals={appeals} />, logging: <Logging config={config} resources={resources} logs={logs} save={save} />, bot: <BotSettings config={config} resources={resources} save={save} />, commands: <Commands /> };
  return <><StatusStrip config={config} />{pages[view]}</>;
}

function StatusStrip({ config }: { config: GuildConfig }) { return <div className="status-strip"><span><i className={config.mode} />MODE <b>{config.mode}</b></span><span>INTENSITY <b>{config.strictness}</b></span><span>AI REVIEW <b>{config.aiEnabled ? 'on' : 'off'}</b></span><span>REPORTS <b>{config.reportedMessageBehavior}</b></span></div>; }
function Heading({ index, title, text }: { index: string; title: string; text: string }) { return <div className="page-heading"><span>{index}</span><div><h1>{title}</h1><p>{text}</p></div></div>; }
function Card({ title, icon, children, className = '' }: { title: string; icon: ReactNode; children: ReactNode; className?: string }) { return <section className={`card ${className}`}><header>{icon}<h2>{title}</h2><span /></header><div className="card-body">{children}</div></section>; }

function Automod({ config, resources, save }: { config: GuildConfig; resources: Resources; save: (patch: Partial<GuildConfig>) => Promise<void> }) {
  const [draft, setDraft] = useState(config); useEffect(() => setDraft(config), [config]); const channels = channelOptions(resources);
  return <><Heading index="01" title="Auto moderation" text="Detection, enforcement, and member notifications." /><div className="layout-grid"><div className="main-stack">
    <Card title="Enforcement" icon={<Siren />}><Field label="Mode" text="Standby sends cases to staff. Active applies the progression ladder."><Segment value={draft.mode} options={[{ value: 'standby', label: 'Standby' }, { value: 'active', label: 'Active' }]} set={(mode) => setDraft({ ...draft, mode: mode as GuildConfig['mode'] })} /></Field><Field label="Intensity" text="Controls when uncertain messages are sent for model review."><Segment value={draft.strictness} options={['low', 'medium', 'high'].map((value) => ({ value, label: value }))} set={(strictness) => setDraft({ ...draft, strictness: strictness as Strictness })} /></Field><Field label="Reported messages in standby" text="Choose whether user reports remain staff-only or can enforce immediately."><Segment value={draft.reportedMessageBehavior} options={[{ value: 'report', label: 'Report only' }, { value: 'enforce', label: 'Take action' }]} set={(reportedMessageBehavior) => setDraft({ ...draft, reportedMessageBehavior: reportedMessageBehavior as GuildConfig['reportedMessageBehavior'] })} /></Field></Card>
    <Card title="Detection" icon={<ShieldCheck />}><Toggle label="AI review" text="Escalate context-heavy messages after local screening." checked={draft.aiEnabled} set={(aiEnabled) => setDraft({ ...draft, aiEnabled })} /><Toggle label="Common swear-word filter" text="Match built-in profanity, slurs, and common evasions." checked={draft.badWordsEnabled} set={(badWordsEnabled) => setDraft({ ...draft, badWordsEnabled })} /><Toggle label="Delete spam" text="Remove repeated floods, mass mentions, and repetition spam." checked={draft.deleteSpamMessages} set={(deleteSpamMessages) => setDraft({ ...draft, deleteSpamMessages })} /><Toggle label="Administrator bypass" text="Skip automatic checks for server administrators." checked={draft.adminBypass} set={(adminBypass) => setDraft({ ...draft, adminBypass })} /></Card>
    <Card title="Custom blocked terms" icon={<MessageSquareWarning />}><Field label="One word or phrase per line" text="Punctuation, spacing, zero-width characters, and basic leetspeak are normalized before matching."><textarea rows={10} value={draft.blockedTerms.join('\n')} onChange={(event) => setDraft({ ...draft, blockedTerms: [...new Set(event.target.value.split('\n').map((item) => item.trim()).filter(Boolean))].slice(0, 500) })} /></Field></Card>
  </div><aside className="side-stack"><Card title="Destinations" icon={<Hash />}><Field label="Moderator reports" text="Staff-only queue for standby cases."><Dropdown value={draft.moderatorChannelId ?? ''} options={channels} placeholder="Choose channel" onChange={(moderatorChannelId) => setDraft({ ...draft, moderatorChannelId: moderatorChannelId || null })} /></Field><Field label="Appeals" text="Appeal notifications can use a separate channel."><Dropdown value={draft.appealsChannelId ?? ''} options={channels} placeholder="Use moderator channel" onChange={(appealsChannelId) => setDraft({ ...draft, appealsChannelId: appealsChannelId || null })} /></Field></Card><Card title="Member notice" icon={<Bell />}><Toggle label="Direct message" text="DM the reason and case number." checked={draft.dmOffenders} set={(dmOffenders) => setDraft({ ...draft, dmOffenders })} /><Toggle label="Channel ping" text="Ping the member when action is taken." checked={draft.pingOffenders} set={(pingOffenders) => setDraft({ ...draft, pingOffenders })} /></Card><SaveButton save={() => save(draft)} /></aside></div></>;
}

const actionOptions: Option[] = [{ value: 'warn', label: 'Warning' }, { value: 'delete', label: 'Delete message' }, { value: 'mute', label: 'Mute' }, { value: 'temp_ban', label: 'Temporary ban' }, { value: 'kick', label: 'Kick' }, { value: 'ban', label: 'Permanent ban' }];
function Progression({ config, save }: { config: GuildConfig; save: (patch: Partial<GuildConfig>) => Promise<void> }) {
  const [levels, setLevels] = useState(config.progressionLevels); const [expiry, setExpiry] = useState<number | null>(config.pcExpiryDays); useEffect(() => { setLevels(config.progressionLevels); setExpiry(config.pcExpiryDays); }, [config.progressionLevels, config.pcExpiryDays]);
  const update = (index: number, level: ProgressionLevel) => setLevels(levels.map((item, i) => i === index ? level : item));
  return <><Heading index="02" title="Progression ladder" text="First offense: verbal warning. Second offense: official warning and PC1. Every offense after that advances the ladder." /><div className="expiry-bar"><div><b>PC expiry</b><span>Each PC point clears separately after the selected time.</span></div><Segment value={expiry == null ? 'permanent' : 'timed'} options={[{ value: 'permanent', label: 'Permanent' }, { value: 'timed', label: 'Expires' }]} set={(value) => setExpiry(value === 'permanent' ? null : 90)} />{expiry != null && <label><input type="number" min="30" max="365" value={expiry} onChange={(event) => setExpiry(Math.min(365, Math.max(30, Number(event.target.value) || 30)))} /> days</label>}</div><div className="ladder-head"><div><b>{levels.length}</b><span>configured levels / 10 maximum</span></div><button disabled={levels.length >= 10} onClick={() => setLevels([...levels, { level: levels.length + 1, label: `PC${levels.length + 1}`, actions: [{ type: 'warn' }] }])}><Plus />Add level</button></div><div className="ladder">
    {levels.map((level, index) => <article className="ladder-row" key={level.level}><div className="pc-index"><span>PC</span><b>{level.level}</b></div><div className="level-content"><input className="level-name" value={level.label} onChange={(event) => update(index, { ...level, label: event.target.value })} /><div className="punishments">{level.actions.map((action, actionIndex) => <PunishmentEditor key={`${level.level}-${actionIndex}`} value={action} change={(next) => update(index, { ...level, actions: level.actions.map((item, i) => i === actionIndex ? next : item) })} remove={() => update(index, { ...level, actions: level.actions.filter((_, i) => i !== actionIndex) })} />)}<button className="add-action" disabled={level.actions.length >= 6} onClick={() => update(index, { ...level, actions: [...level.actions, { type: 'warn' }] })}><Plus />Add action</button></div></div>{levels.length > 1 && index === levels.length - 1 && <button className="remove-level" title="Remove level" onClick={() => setLevels(levels.slice(0, -1))}><Trash2 /></button>}</article>)}
  </div><div className="save-dock"><p>Changes affect the next offense. Existing cases are not rewritten.</p><SaveButton save={() => save({ pcExpiryDays: expiry, progressionLevels: levels.map((level, index) => ({ ...level, level: index + 1 })) })} /></div></>;
}
function PunishmentEditor({ value, change, remove }: { value: ProgressionPunishment; change: (value: ProgressionPunishment) => void; remove: () => void }) { const duration = value.durationMinutes == null ? '' : formatMinutes(value.durationMinutes); return <div className="punishment"><Dropdown value={value.type} options={actionOptions} placeholder="Action" onChange={(type) => change({ type: type as PunishmentType, ...(['mute', 'temp_ban'].includes(type) ? { durationMinutes: value.durationMinutes ?? 60 } : {}) })} />{['mute', 'temp_ban'].includes(value.type) && <input value={duration} placeholder="1h / 14d / blank = indefinite" onChange={(event) => change({ ...value, durationMinutes: parseDuration(event.target.value) })} />}<button onClick={remove} title="Remove action"><X /></button></div>; }

function Cases({ cases, appeals }: { cases: ModerationCase[]; appeals: Appeal[] }) { const [query, setQuery] = useState(''); const filtered = cases.filter((item) => `${item.id} ${item.userId} ${item.reason}`.toLowerCase().includes(query.toLowerCase())); return <><Heading index="03" title="Cases & appeals" text="Every action has a case number. Appeals are resolved in Discord with /appeal approve or /appeal deny." /><SearchBox value={query} set={setQuery} placeholder="Search case number, member, or reason" /><div className="case-layout"><Card title="Cases" icon={<Gavel />}>{filtered.length ? filtered.map((item) => <div className="case-item" key={item.id}><span className={`risk ${item.severity}`}><Shield /></span><div><b>#{item.id.slice(0, 8)} · {item.action.replace('_', ' ')}</b><p>{item.reason}</p><small>Member {item.userId} · PC {item.pcBefore} → {item.pcAfter}</small></div><time>{relative(item.createdAt)}</time></div>) : <Empty icon={<CircleSlash />} title="No matching cases" text="New moderation cases will appear here." />}</Card><Card title="Appeals" icon={<FileClock />} className="appeal-card">{appeals.length ? appeals.map((item) => <div className="appeal-item" key={item.id}><span className={item.status}>{item.status}</span><div><b>Case #{item.caseId.slice(0, 8)}</b><p>{item.reason}</p><small>Member {item.userId} · {relative(item.createdAt)}</small></div></div>) : <Empty icon={<FileClock />} title="No appeals" text="Submitted appeals will appear here." />}</Card></div></>; }

function Logging({ config, resources, logs, save }: { config: GuildConfig; resources: Resources; logs: AuditLog[]; save: (patch: Partial<GuildConfig>) => Promise<void> }) { const [channel, setChannel] = useState(config.loggingChannelId ?? ''); useEffect(() => setChannel(config.loggingChannelId ?? ''), [config.loggingChannelId]); return <><Heading index="04" title="Logging" text="A single, readable Discord record for moderation and server activity." /><div className="layout-grid"><Card title="Log channel" icon={<FileText />}><Field label="Destination" text="Reports, punishments, appeals, deleted and edited messages, member events, and configuration changes go here."><Dropdown value={channel} options={channelOptions(resources)} placeholder="Choose channel" onChange={setChannel} /></Field><div className="covered-events">{['Reports with message evidence', 'Warnings, mutes, kicks, and bans', 'Appeals and reversals', 'Deleted and edited messages', 'Member and voice events', 'Dashboard configuration changes'].map((item) => <span key={item}><Check />{item}</span>)}</div><SaveButton save={() => save({ loggingChannelId: channel || null })} /></Card><Card title="Recent log" icon={<Activity />}><div className="recent-log">{logs.slice(0, 12).map((item) => <div key={item.id}><time>{relative(item.createdAt)}</time><span>{item.summary}</span></div>)}{!logs.length && <Empty icon={<FileText />} title="No log entries" text="Activity will appear here." />}</div></Card></div></>; }

function BotSettings({ config, resources, save }: { config: GuildConfig; resources: Resources; save: (patch: Partial<GuildConfig>) => Promise<void> }) { const [prefixes, setPrefixes] = useState(config.prefixes); const [next, setNext] = useState(''); const [cooldown, setCooldown] = useState(String(config.appealCooldownMinutes)); useEffect(() => { setPrefixes(config.prefixes); setCooldown(String(config.appealCooldownMinutes)); }, [config]); return <><Heading index="05" title="Bot settings" text="Command entry points and server-wide appeal controls." /><div className="layout-grid"><Card title="Command prefixes" icon={<Hash />}><Field label="Add prefix" text="Slash commands always remain available. Up to eight custom prefixes can be active."><div className="input-row"><input maxLength={5} value={next} onChange={(event) => setNext(event.target.value)} /><button onClick={() => { if (next && !prefixes.includes(next)) setPrefixes([...prefixes, next]); setNext(''); }}><Plus />Add</button></div></Field><div className="prefix-grid">{prefixes.map((item) => <span key={item}><code>{item}</code><button disabled={prefixes.length === 1} onClick={() => setPrefixes(prefixes.filter((prefix) => prefix !== item))}><X /></button></span>)}</div><SaveButton save={() => save({ prefixes })} /></Card><Card title="Appeal control" icon={<FileClock />}><Field label="User cooldown in minutes" text="Rate limit between appeal submissions per member."><input type="number" min="1" max="10080" value={cooldown} onChange={(event) => setCooldown(event.target.value)} /></Field><Field label="Appeal channel" text="Defaults to the moderator report channel when unset."><Dropdown value={config.appealsChannelId ?? ''} options={channelOptions(resources)} placeholder="Use moderator channel" onChange={(appealsChannelId) => void save({ appealsChannelId: appealsChannelId || null })} /></Field><SaveButton save={() => save({ appealCooldownMinutes: Math.min(10080, Math.max(1, Number(cooldown) || 360)) })} /></Card></div></>; }

function Commands() { const [query, setQuery] = useState(''); const list = useMemo(() => COMMAND_CATALOG.filter((item) => `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [query]); return <><Heading index="06" title="Commands" text="Slash commands, prefix equivalents, mentions, and access level." /><SearchBox value={query} set={setQuery} placeholder="Search commands" /><Card title={`${list.length} commands`} icon={<Command />}><div className="command-list">{list.map((item) => <div key={item.name}><code>/{item.name}</code><span>{item.description}</span><b>{item.moderatorOnly ? 'MOD' : 'ALL'}</b></div>)}</div></Card></>; }

function Field({ label, text, children }: { label: string; text: string; children: ReactNode }) { return <div className="field"><label>{label}</label><p>{text}</p>{children}</div>; }
function Toggle({ label, text, checked, set }: { label: string; text: string; checked: boolean; set: (value: boolean) => void }) { return <div className="toggle-row"><div><b>{label}</b><p>{text}</p></div><button role="switch" aria-checked={checked} className={checked ? 'toggle on' : 'toggle'} onClick={() => set(!checked)}><i /></button></div>; }
function Segment({ value, options, set }: { value: string; options: Option[]; set: (value: string) => void }) { return <div className="segment">{options.map((item) => <button key={item.value} className={item.value === value ? 'selected' : ''} onClick={() => set(item.value)}>{item.label}</button>)}</div>; }
function SaveButton({ save }: { save: () => Promise<void> }) { const [state, setState] = useState<'idle' | 'saving' | 'saved'>('idle'); return <button className="save" disabled={state === 'saving'} onClick={() => { setState('saving'); void save().then(() => { setState('saved'); setTimeout(() => setState('idle'), 1400); }).catch(() => setState('idle')); }}>{state === 'saved' ? <Check /> : <Save />}{state === 'saving' ? 'Saving' : state === 'saved' ? 'Saved' : 'Save changes'}</button>; }
function Dropdown({ value, options, placeholder, onChange, compact = false }: { value: string; options: Option[]; placeholder: string; onChange: (value: string) => void; compact?: boolean }) { const [open, setOpen] = useState(false); const selected = options.find((item) => item.value === value); return <div className={`dropdown ${compact ? 'compact' : ''}`}><button className="dropdown-trigger" aria-expanded={open} onClick={() => setOpen(!open)}><span>{selected?.label ?? placeholder}</span><ChevronDown /></button>{open && <div className="dropdown-menu">{options.length ? options.map((item) => <button key={item.value} className={item.value === value ? 'selected' : ''} onClick={() => { onChange(item.value); setOpen(false); }}>{item.label}{item.value === value && <Check />}</button>) : <span>No options available</span>}</div>}</div>; }
function SearchBox({ value, set, placeholder }: { value: string; set: (value: string) => void; placeholder: string }) { return <div className="search-box"><Search /><input value={value} placeholder={placeholder} onChange={(event) => set(event.target.value)} /></div>; }
function Empty({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="empty">{icon}<b>{title}</b><span>{text}</span></div>; }
function Loading({ compact = false }: { compact?: boolean }) { return <div className={`loading ${compact ? 'compact' : ''}`}><LoaderCircle /><span>Loading</span></div>; }
function Logo() { return <div className="logo"><span>A</span><b>APEXBOT</b></div>; }
function DiscordMark() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M19.5 5.34A17.2 17.2 0 0 0 15.23 4l-.53 1.08a15.7 15.7 0 0 0-5.4 0L8.77 4A17.2 17.2 0 0 0 4.5 5.34C1.8 9.36 1.07 13.28 1.43 17.15a17.4 17.4 0 0 0 5.24 2.65l1.27-1.74a10.5 10.5 0 0 1-1.99-.95l.49-.38a12.3 12.3 0 0 0 11.12 0l.49.38c-.64.38-1.3.7-2 .95l1.28 1.74a17.4 17.4 0 0 0 5.24-2.65c.43-4.49-.74-8.37-3.07-11.81ZM8.25 14.75c-1.02 0-1.85-.94-1.85-2.1 0-1.15.81-2.09 1.85-2.09s1.87.95 1.85 2.09c0 1.16-.82 2.1-1.85 2.1Zm7.5 0c-1.02 0-1.85-.94-1.85-2.1 0-1.15.81-2.09 1.85-2.09s1.87.95 1.85 2.09c0 1.16-.81 2.1-1.85 2.1Z" /></svg>; }
function channelOptions(resources: Resources): Option[] { return resources.channels.map((item) => ({ value: item.id, label: `#${item.name}` })); }
function relative(value: string) { const s = Math.max(0, Math.floor((Date.now() - Date.parse(value)) / 1000)); return s < 60 ? `${s}s ago` : s < 3600 ? `${Math.floor(s / 60)}m ago` : s < 86400 ? `${Math.floor(s / 3600)}h ago` : `${Math.floor(s / 86400)}d ago`; }
function formatMinutes(minutes: number) { if (minutes % 525_960 === 0) return `${minutes / 525_960}y`; if (minutes % 10_080 === 0) return `${minutes / 10_080}w`; if (minutes % 1_440 === 0) return `${minutes / 1_440}d`; if (minutes % 60 === 0) return `${minutes / 60}h`; return `${minutes}m`; }
function parseDuration(value: string): number | null { if (!value.trim()) return null; const match = value.trim().match(/^(\d+(?:\.\d+)?)\s*([smhdwy])$/i); if (!match) return 60; const n = Number(match[1]); const factor = ({ s: 1 / 60, m: 1, h: 60, d: 1_440, w: 10_080, y: 525_960 } as const)[match[2]!.toLowerCase() as 's']; return Math.min(52_596_000, n * factor); }
